### ISSUE TITLE
Text missing for some pdf files

### ISSUE THREAD

**Issue by Juviro** [ksami/pdftoimage#1]
Hello,

I'm having issues converting some pdfs to png. Most files are working flawlessly, but converting the attached pdf will create a png that contains all the images, but all of the text is missing.
Any ideas how to fix that?

Thanks 

[Example Pdf](https://github.com/ksami/pdftoimage/files/2266367/textMissing.pdf)
[Output png](https://user-images.githubusercontent.com/11948240/43776363-e2827e20-9a4f-11e8-9c17-01b5f7280cf7.png)

Edit: Found the solution: My docker container ran an outdated version of poppler-utils, works fine after upgrading

**Comment by ksami** [comment]
Thanks for adding your solution before closing the issue, I'm sure someone somewhere in the future will appreciate this very much.
